### PR TITLE
upgrade ios sdk to 5.8.1/android sdk to 5.7.0

### PR DESCRIPTION
**Pull request by blackbing**
#### 🔄 Type of change:

- [x] ✨Feature/chore
- [ ] :recycle: Refactor
- [ ] :wrench: Bugfixes

---

#### :pencil2: Description:

The library SK is out of date. There are newer version to upgrade. Besides, 
#### IOS
we don't need `use_frameworks!` if react-native >= 0.63. 
#### Android
the namespace was changed. `com.linecorp:linesdk` -> `com.linecorp.linesdk:linesdk:`

---

#### :pushpin: Notes:

- for anyone who need to use the latest SDK directly, feel free to use our repo 

```
yarn add verybuy/react-native-line#8dcc99d
```

because we don't have publish permission @xmartlabs/react-native-line, so we build the dist and push to our repo.

You can also checkout the commit. https://github.com/VeryBuy/react-native-line/commits/feature/verybuy

---

#### :heavy_check_mark:Tasks:

- we have integrated in our project and it works. 
---

### CODE REVIEW

**Comment by dienhungptit** [comment]
Have a good day, great to see your hard work! 
I'm currently doing Line Authentication in my React-Native App, and I can not find any good Repo like yours. But I still not implement right :D Can you make a doc/tutorial on using your repo. Thank you very much.

**Comment by blackbing** [comment]
> 

@dienhungptit I update the README. please checkout the diff

https://github.com/xmartlabs/react-native-line/pull/90/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by dienhungptit** [comment]
Tks pro.

**Comment by phuocantd** [comment]
error when build android
```
* What went wrong:
Execution failed for task ':xmartlabs_react-native-line:compileDebugKotlin'.
> Compilation error. See log for more details
```

how to work on Android and iOS
I using react 18.2.0 and react-native 0.69.1

**Comment by blackbing** [comment]
> @blackbing error when build android
> 
> ```
> * What went wrong:
> Execution failed for task ':xmartlabs_react-native-line:compileDebugKotlin'.
> > Compilation error. See log for more details
> ```
> 
> how to work on Android and iOS I using react 18.2.0 and react-native 0.69.1

Do you install our fork repo? 
```
yarn add verybuy/react-native-line#8dcc99d

```

**Comment by blackbing** [comment]
Have you done Android setup? https://github.com/VeryBuy/react-native-line/tree/feat/upgrade-sdk#android-setup

**Comment by phuocantd** [comment]
> Have you done Android setup? https://github.com/VeryBuy/react-native-line/tree/feat/upgrade-sdk#android-setup

@blackbing  work on iOS when downgrade react-native version 0.67.2 but Android I setup follow you but open popup then display error

**Comment by phuocantd** [comment]
@blackbing you can check in this repo
https://github.com/phuocantd/RNLine

**Comment by phuocantd** [comment]
@blackbing  I found the cause, because it doesn't match the package name. I hope you will update react native version 0.69 soon

**Comment by blackbing** [comment]
I see. Our project use react-native@0.67. when we upgrade to 0.69 above, I will take a look the problem. I think it might do some migrate task like this. 
https://reactnative.dev/blog/2022/06/16/resources-migrating-your-react-native-library-to-the-new-architecture

**Comment by VanDinh18** [comment]
@phuocantd i have error on Android "xmartlabs_react-native-line:compileDebugKotlin". How to fix it

**Comment by phuocantd** [comment]
> @phuocantd i have error on Android "xmartlabs_react-native-line:compileDebugKotlin". How to fix it

what's version react native you use?

**Comment by baby230211** [comment]
@phuocantd @blackbing 
i had followed Android setup follow but open popup then display error
but i think i set the correct android packageName on developer console (com.myapp.linelogin).
How to fix it?

**Review by emibotti — COMMENTED** [review]
Thank you so much for contributing! 
Sorry for the very late response, the idea is to go back to maintaining the repo.
I suppose you won't be doing any of these changes because of how much time has passed since you opened it.
I will merge these changes to a new branch and work on it to merge it to `master` as soon as possible and do a release to make it available to all the devs.
Thank you again!! Your fork was able to help so many developers in the meantime 🙏
